=== germanarcos/LM/xml/25. Ejercicios DTD Avanzados/dtd5.dtd
<!ELEMENT videoclub (factura*)>
<!ELEMENT factura (datos_cliente, datos_factura)>
<!ELEMENT datos_cliente (nombre, primer_apellido, segundo_apellido, DNI, telefono, identificador_cliente)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT primer_apellido (#PCDATA)>
<!ELEMENT segundo_apellido (#PCDATA)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT identificador_cliente (#PCDATA)>

<!ELEMENT datos_factura (alquiler, compra, resguardo)>
<!ELEMENT alquiler (pelicula)*>
<!ATTLIST alquiler devolucion CDATA #REQUIRED>
<!ELEMENT pelicula (titulo, genero, duracion, reparto)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT duracion EMPTY>
<!ATTLIST duracion valor CDATA #REQUIRED>

<!ELEMENT reparto (actor*)>
<!ELEMENT actor (nombre, primer_apellido)>

<!ELEMENT compra (DVD | cinta)*>
<!ELEMENT DVD (titulo, fecha_salida, extras?)>
<!ELEMENT fecha_salida EMPTY>
<!ELEMENT extras EMPTY>
<!ATTLIST fecha_salida fecha CDATA #IMPLIED>

<!ELEMENT cinta (titulo, formato, rebobinada)>
<!ELEMENT formato EMPTY>
<!ATTLIST formato tipo CDATA #REQUIRED>
<!ELEMENT rebobinada EMPTY>
<!ATTLIST rebobinada valor (Si|No) #REQUIRED>
<!ELEMENT resguardo (forma_pago, importe_total)>
<!ELEMENT forma_pago EMPTY>
<!ATTLIST forma_pago forma (Tarjeta | Efectivo) #REQUIRED>
<!ELEMENT importe_total (#PCDATA)>

=== germanarcos/LM/xml/25. Ejercicios DTD Avanzados/xml5.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE videoclub SYSTEM "dtd5.dtd">
<videoclub>
	<factura>
		<datos_cliente>
			<nombre>
				Paco
			</nombre>
			<primer_apellido>
				Paquito
			</primer_apellido>
			<segundo_apellido>
				Paquete
			</segundo_apellido>
			<DNI>
				12873412W
			</DNI>
			<telefono>
				612345789
			</telefono>
			<identificador_cliente>
				1234WR
			</identificador_cliente>
		</datos_cliente>
		<datos_factura>
			<alquiler devolucion="29/01/2018">
				<pelicula>
					<titulo>
						SHARKNADO
					</titulo>
					<genero>
						comedia
					</genero>
					<duracion valor="178"/>
					<reparto>
						<actor>
							<nombre>
								Tiburon blanco
							</nombre>
							<primer_apellido>
								Ochenta kilos
							</primer_apellido>
						</actor>
						<actor>
							<nombre>
								La yuyee
							</nombre>
							<primer_apellido>
								Sacarla
							</primer_apellido>
						</actor>
						<actor>
							<nombre>
								Frank
							</nombre>
							<primer_apellido>
								Cuesta
							</primer_apellido>
						</actor>
					</reparto>
				</pelicula>
			</alquiler>
			<compra>
				<DVD>
					<titulo>
						No se que poner ya
					</titulo>
					<fecha_salida fecha=""/>
					<extras/>
				</DVD>
				<cinta>
					<titulo>
						Relleno
					</titulo>
					<formato tipo="VHS"/>
					<rebobinada valor="Si"/>
				</cinta>
			</compra>
			<resguardo>
				<forma_pago forma="Efectivo"/>
				<importe_total>
					0.000000000005â‚¬
				</importe_total>
			</resguardo>
		</datos_factura>
	</factura>
</videoclub>
