<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE personas [<!ELEMENT personas (persona*)>
<!ELEMENT persona (nombre, nacimiento, direccion, ( varon| mujer) )>
<!ELEMENT direccion (calle, poblacion, provincia, cpostal)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cpostal (#PCDATA)>
<!ELEMENT nacimiento EMPTY>
<!ATTLIST nacimiento
dia CDATA #REQUIRED
mes (Enero | Febrero | Marzo | Abril | Mayo | Junio | Julio | Agosto | Septiembre | Octubre | Noviembre |Diciembre ) #REQUIRED
 anyo CDATA #REQUIRED>
<!ELEMENT varon EMPTY>
<!ELEMENT mujer EMPTY>]>
<personas>
	<persona>
		<nombre>
			Juan Pardo
		</nombre>
		<nacimiento dia="10" mes="Abril" anyo="1982"/>
		<direccion>
			<calle>
				Caoba,1
			</calle>
			<poblacion>
				Madrid
			</poblacion>
			<provincia>
				Madrid
			</provincia>
			<cpostal>
				28005
			</cpostal>
		</direccion>
		<varon/>
	</persona>

	<persona>
		<nombre>
			Homer Simpson
		</nombre>
		<nacimiento dia="7" mes="Julio" anyo="1995"/>
		<direccion>
			<calle>
				Falsa 123
			</calle>
			<poblacion>
				Alicante
			</poblacion>
			<provincia>
				Alicante
			</provincia>
			<cpostal>
				00301
			</cpostal>
		</direccion>
		<mujer/>
	</persona>
</personas>